[package]
name = "contract"
version = "0.2.0"
edition = "2024"

[dependencies]
firefly-balius = { path = "../firefly-cardano/firefly-balius" }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.141"

[lib]
crate-type = ["cdylib"]
